[package]
name = "libsrt-sys"
version = "1.5.3"
edition = "2021"

# rust bind


[build-dependencies]
bindgen = "0.70.1"
reqwest = { version = "0.12.7", features = ["blocking"] }
flate2 = "1.0"
tar = "0.4"
cc = "1.0.99"
