[package]
name = "libsrt-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
os_socketaddr = "0.2.5" # https://github.com/a-ba/os_socketaddr
libsrt-sys = { path = "libsrt-sys", version = "1.5.3" }
libc = "0.2"
futures = "0.3"
