#[repr(C)]
pub struct SrtTraceBStats {
    pub msTimeStamp: i64,
    pub pktSentTotal: i64,
    pub pktRecvTotal: i64,
    pub pktSndLossTotal: i32,
    pub pktRcvLossTotal: i32,
    pub pktRetransTotal: i32,
    pub pktSentACKTotal: i32,
    pub pktRecvACKTotal: i32,
    pub pktSentNAKTotal: i32,
    pub pktRecvNAKTotal: i32,
    pub usSndDurationTotal: i64,
    pub pktSndDropTotal: i32,
    pub pktRcvDropTotal: i32,
    pub pktRcvUndecryptTotal: i32,
    pub byteSentTotal: u64,
    pub byteRecvTotal: u64,
    pub byteRcvLossTotal: u64,
    pub byteRetransTotal: u64,
    pub byteSndDropTotal: u64,
    pub byteRcvDropTotal: u64,
    pub byteRcvUndecryptTotal: u64,
    pub pktSent: i64,
    pub pktRecv: i64,
    pub pktSndLoss: i32,
    pub pktRcvLoss: i32,
    pub pktRetrans: i32,
    pub pktRcvRetrans: i32,
    pub pktSentACK: i32,
    pub pktRecvACK: i32,
    pub pktSentNAK: i32,
    pub pktRecvNAK: i32,
    pub mbpsSendRate: f64,
    pub mbpsRecvRate: f64,
    pub usSndDuration: i64,
    pub pktReorderDistance: i32,
    pub pktRcvAvgBelatedTime: f64,
    pub pktRcvBelated: i64,
    pub pktSndDrop: i32,
    pub pktRcvDrop: i32,
    pub pktRcvUndecrypt: i32,
    pub byteSent: u64,
    pub byteRecv: u64,
    pub byteRcvLoss: u64,
    pub byteRetrans: u64,
    pub byteSndDrop: u64,
    pub byteRcvDrop: u64,
    pub byteRcvUndecrypt: u64,
    pub usPktSndPeriod: f64,
    pub pktFlowWindow: i32,
    pub pktCongestionWindow: i32,
    pub pktFlightSize: i32,
    pub msRTT: f64,
    pub mbpsBandwidth: f64,
    pub byteAvailSndBuf: i32,
    pub byteAvailRcvBuf: i32,
    pub mbpsMaxBW: f64,
    pub byteMSS: i32,
    pub pktSndBuf: i32,
    pub byteSndBuf: i32,
    pub msSndBuf: i32,
    pub msSndTsbPdDelay: i32,
    pub pktRcvBuf: i32,
    pub byteRcvBuf: i32,
    pub msRcvBuf: i32,
    pub msRcvTsbPdDelay: i32,
    pub pktSndFilterExtraTotal: i32,
    pub pktRcvFilterExtraTotal: i32,
    pub pktRcvFilterSupplyTotal: i32,
    pub pktRcvFilterLossTotal: i32,
    pub pktSndFilterExtra: i32,
    pub pktRcvFilterExtra: i32,
    pub pktRcvFilterSupply: i32,
    pub pktRcvFilterLoss: i32,
    pub pktReorderTolerance: i32,
}

impl SrtTraceBStats {
    pub fn new() -> Self {
        unsafe { std::mem::zeroed() }
    }
}